// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class Cliente
{
    public int id_cliente { get; set; }

    public string nombre { get; set; }

    public string tipo { get; set; }

    public string ruc { get; set; }

    public string contacto { get; set; }

    public int? zona_id { get; set; }

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();

    public virtual Zona zona { get; set; }
}