// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class DetallePedido
{
    public int id_detalle { get; set; }

    public int? pedido_id { get; set; }

    public int? producto_id { get; set; }

    public int? cantidad { get; set; }

    public decimal? subtotal { get; set; }

    public virtual Pedido pedido { get; set; }

    public virtual Producto producto { get; set; }
}