// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class Entrega
{
    public int id_entrega { get; set; }

    public int? pedido_id { get; set; }

    public int? repartidor_id { get; set; }

    public DateTime? fecha_entrega { get; set; }

    public string estado { get; set; }

    public string observaciones { get; set; }

    public virtual Pedido pedido { get; set; }

    public virtual Usuario repartidor { get; set; }
}