// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class Pedido
{
    public int id_pedido { get; set; }

    public int? cliente_id { get; set; }

    public DateTime? fecha { get; set; }

    public string estado { get; set; }

    public decimal? total { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual Entrega Entrega { get; set; }

    public virtual Cliente cliente { get; set; }
}