// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class Ruta
{
    public int id_ruta { get; set; }

    public int? zona_id { get; set; }

    public int? vehiculo_id { get; set; }

    public DateOnly? fecha { get; set; }

    public string descripcion { get; set; }

    public virtual Vehiculo vehiculo { get; set; }

    public virtual Zona zona { get; set; }
}