// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class Usuario
{
    public int id_usuario { get; set; }

    public string nombre { get; set; }

    public string username { get; set; }

    public string contrasena { get; set; }

    public string rol { get; set; }

    public virtual ICollection<Entrega> Entrega { get; set; } = new List<Entrega>();
}