// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class Vehiculo
{
    public int id_vehiculo { get; set; }

    public string placa { get; set; }

    public string marca { get; set; }

    public int? capacidad { get; set; }

    public virtual ICollection<Ruta> Ruta { get; set; } = new List<Ruta>();
}