// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class Zona
{
    public int id_zona { get; set; }

    public string nombre { get; set; }

    public virtual ICollection<Cliente> Cliente { get; set; } = new List<Cliente>();

    public virtual ICollection<Ruta> Ruta { get; set; } = new List<Ruta>();
}