// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dulceria.Infraestructura.AccesoDatos;

public partial class DulceFacilDBContext : DbContext
{
    public DulceFacilDBContext()
    {
    }

    public DulceFacilDBContext(DbContextOptions<DulceFacilDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<DetallePedido> DetallePedido { get; set; }

    public virtual DbSet<Entrega> Entrega { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Ruta> Ruta { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Vehiculo> Vehiculo { get; set; }

    public virtual DbSet<Zona> Zona { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=Home;Initial Catalog=DulceFacilDB;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.id_cliente).HasName("PK__Cliente__677F38F5DDFE430C");

            entity.Property(e => e.contacto).HasMaxLength(100);
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.ruc).HasMaxLength(20);
            entity.Property(e => e.tipo).HasMaxLength(20);

            entity.HasOne(d => d.zona).WithMany(p => p.Cliente)
                .HasForeignKey(d => d.zona_id)
                .HasConstraintName("FK__Cliente__zona_id__398D8EEE");
        });

        modelBuilder.Entity<DetallePedido>(entity =>
        {
            entity.HasKey(e => e.id_detalle).HasName("PK__DetalleP__4F1332DEDD225FF8");

            entity.Property(e => e.subtotal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.pedido).WithMany(p => p.DetallePedido)
                .HasForeignKey(d => d.pedido_id)
                .HasConstraintName("FK__DetallePe__pedid__412EB0B6");

            entity.HasOne(d => d.producto).WithMany(p => p.DetallePedido)
                .HasForeignKey(d => d.producto_id)
                .HasConstraintName("FK__DetallePe__produ__4222D4EF");
        });

        modelBuilder.Entity<Entrega>(entity =>
        {
            entity.HasKey(e => e.id_entrega).HasName("PK__Entrega__017C2C8A2F2E6A38");

            entity.HasIndex(e => e.pedido_id, "UQ__Entrega__CBE7607770F62E74").IsUnique();

            entity.Property(e => e.estado).HasMaxLength(20);
            entity.Property(e => e.fecha_entrega).HasColumnType("datetime");
            entity.Property(e => e.observaciones).HasMaxLength(255);

            entity.HasOne(d => d.pedido).WithOne(p => p.Entrega)
                .HasForeignKey<Entrega>(d => d.pedido_id)
                .HasConstraintName("FK__Entrega__pedido___4E88ABD4");

            entity.HasOne(d => d.repartidor).WithMany(p => p.Entrega)
                .HasForeignKey(d => d.repartidor_id)
                .HasConstraintName("FK__Entrega__reparti__4F7CD00D");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasKey(e => e.id_pedido).HasName("PK__Pedido__6FF014896B1E236B");

            entity.Property(e => e.estado).HasMaxLength(20);
            entity.Property(e => e.fecha).HasColumnType("datetime");
            entity.Property(e => e.total).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.cliente).WithMany(p => p.Pedido)
                .HasForeignKey(d => d.cliente_id)
                .HasConstraintName("FK__Pedido__cliente___3E52440B");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__Producto__FF341C0DD9588139");

            entity.Property(e => e.descripcion).HasMaxLength(200);
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.precio).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.unidad).HasMaxLength(20);
        });

        modelBuilder.Entity<Ruta>(entity =>
        {
            entity.HasKey(e => e.id_ruta).HasName("PK__Ruta__33C9344F81942EE0");

            entity.Property(e => e.descripcion).HasMaxLength(200);

            entity.HasOne(d => d.vehiculo).WithMany(p => p.Ruta)
                .HasForeignKey(d => d.vehiculo_id)
                .HasConstraintName("FK__Ruta__vehiculo_i__47DBAE45");

            entity.HasOne(d => d.zona).WithMany(p => p.Ruta)
                .HasForeignKey(d => d.zona_id)
                .HasConstraintName("FK__Ruta__zona_id__46E78A0C");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.id_usuario).HasName("PK__Usuario__4E3E04AD359F4425");

            entity.HasIndex(e => e.username, "UQ__Usuario__F3DBC57218EA788A").IsUnique();

            entity.Property(e => e.contrasena).HasMaxLength(100);
            entity.Property(e => e.nombre).HasMaxLength(100);
            entity.Property(e => e.rol).HasMaxLength(20);
            entity.Property(e => e.username).HasMaxLength(50);
        });

        modelBuilder.Entity<Vehiculo>(entity =>
        {
            entity.HasKey(e => e.id_vehiculo).HasName("PK__Vehiculo__F5DC0F39031EE35C");

            entity.Property(e => e.marca).HasMaxLength(50);
            entity.Property(e => e.placa).HasMaxLength(10);
        });

        modelBuilder.Entity<Zona>(entity =>
        {
            entity.HasKey(e => e.id_zona).HasName("PK__Zona__67C93611A3D23035");

            entity.Property(e => e.nombre).HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}